name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"
    
permissions:
  issues: write
jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 获取用户ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: 设置用户信息
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: 关闭过期问题
        uses: actions/stale@v9
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
          days-before-issue-stale: 60
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "📅 你好 @${{ github.event.issue.user.login }}，这个问题已经过期了，因为它已经开放了30天，没有任何活动。"
          close-issue-message: "🚫 你好 @${{ github.event.issue.user.login }}，此问题已关闭，因为它已被标记为过期后14天处于非活动状态。。"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-pinned: true